name: Windows
on:
  push:
    branches: [ main, test_workflow ]
  pull_request:
    branches: [ main, test_workflow ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022
    
    strategy:
      matrix:
        configuration: [Debug, Release]
        platform: [x64, x86]
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup MSBuild and add to PATH
        uses: microsoft/setup-msbuild@v1.1
        
      - name: Install Cache
        uses: actions/cache@v2
        id: install-cache
        with:
          path: |
            ./Engine/Build/Windows/CMake/*
            ./Engine/Build/Windows/Ninja/*
            ./Engine/Build/Windows/vswhere/*
          key: install-cache-v0
        
      - name: Install
        if: steps.install-cache.outputs.cache-hit != 'true'
        working-directory: .\Engine\Build\Windows\
        run: |
          .\InstallCMake.bat
          .\InstallNinja.bat
          .\InstallVSWhere.bat
          
      - name: Build
        working-directory: .\Engine\Build\Windows\
        run: .\Build.bat ${{ matrix.platform }} ${{ matrix.configuration }}

      - name: Test
        working-directory: .\Engine\Build\Windows\
        run: .\Test.bat ${{ matrix.platform }} ${{ matrix.configuration }}
